# Generated by Django 5.1.4 on 2025-08-20 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_dummydata'),
        ('fleet', '0002_seed'),
    ]

    operations = [
    ]
